version: '2.3'
services:
  app:
    build: 
      context: .
      target: dev
    # command: /app/node_modules/.bin/nodemon
    command: ["/app/node_modules/.bin/nodemon", "--inspect=0.0.0.0:9229", "index.js"]
    ports:
      - 3000:3000
      # - 9229:9229
    volumes:
      - .:/app
    environment:
      NODE_ENV: ${NDE_ENV}
      POSTGRES_HOST: ${PG_HOST}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DATABASE}
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    env_file: ".env"
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:

    